Repository Wedvice/Wedvice_FE, pull requests merged in 2024-12, with the labels that each got.

#5 chromatic CI 설정 및 공통 컴포넌트 설정
  .github/CODEOWNERS
  .github/workflows/chromatic.yml
  .prettierrc
  .storybook/preview.ts
  package.json
  postcss.config.cjs
  public/sw.js
  public/workbox-81865200.js
  public/workbox-dae32412.js
  src/app/favicon.ico
  src/app/fonts/GeistMonoVF.woff
  src/app/fonts/GeistVF.woff
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/atoms/button/Button.stories.tsx
  src/components/atoms/button/Button.tsx
  src/components/atoms/button/index.ts
  src/styles/theme/colors.ts
  src/styles/theme/index.ts
  src/styles/theme/radius.ts
  tailwind.config.ts
  tsconfig.json
  yarn.lock
Labels: 🎨 Design, ✨ Feature, ⚙ Setting

#8 Memo 컴포넌트 추가
  src/components/atoms/memo/Memo.stories.tsx
  src/components/atoms/memo/Memo.tsx
  src/styles/theme/radius.ts
Labels: 🎨 Design, ✨ Feature

#9 [chore] font 설정
  src/app/font.ts
  src/app/layout.tsx
  src/assets/fonts/Pretendard/Pretendard-Black.woff2
  src/assets/fonts/Pretendard/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard/Pretendard-ExtraBold.woff2
  src/assets/fonts/Pretendard/Pretendard-ExtraLight.woff2
  src/assets/fonts/Pretendard/Pretendard-Light.woff2
  src/assets/fonts/Pretendard/Pretendard-Medium.woff2
  src/assets/fonts/Pretendard/Pretendard-Regular.woff2
  src/assets/fonts/Pretendard/Pretendard-SemiBold.woff2
  src/assets/fonts/Pretendard/Pretendard-Thin.woff2
  src/components/atoms/button/Button.stories.tsx
  src/components/atoms/button/Button.tsx
  src/styles/theme/colors.ts
  src/styles/theme/index.ts
  src/styles/theme/radius.ts
  src/styles/theme/spacing.ts
  tailwind.config.ts
Labels: ⚙ Setting, 🖼️ Asset
