Repository Wedvice/Wedvice_FE, pull requests merged in 2025-01, with the labels that each got.

#10 [chore] Axios 설정 및 테스트 API 구현
  package.json
  src/api/axios.ts
  src/api/index.ts
  src/api/test.ts
  src/constants/apiStatus.ts
Labels: ✨ Feature, ⚙ Setting

#12 [feat] navigation component
  package.json
  src/app/home/[username]/layout.tsx
  src/app/home/[username]/page.tsx
  src/app/layout.tsx
  src/assets/navigation/logo.svg
  src/assets/navigation/notification.svg
  src/components/molecules/navigation/Navigation.stories.tsx
  src/components/molecules/navigation/Navigation.tsx
  src/components/molecules/navigation/SubIcon.tsx
  src/components/molecules/navigation/index.ts
  src/features/home/Home.tsx
  src/features/home/index.ts
  yarn.lock
Labels: ✨ Feature, 🖼️ Asset

#14 [feat] 메모 페이지 구현
  public/profile.png
  src/app/layout.tsx
  src/app/memo/[username]/page.tsx
  src/components/atoms/memo/Memo.tsx
  src/components/atoms/memo/MemoDiv.tsx
  src/components/atoms/memo/MemoTextarea.tsx
  src/components/atoms/profile/Profile.tsx
  src/components/molecules/MemoContent.tsx
  src/features/home/Home.tsx
  src/features/memo/Memo.tsx
  src/features/memo/index.ts
Labels: ✨ Feature, 🔨 Refactor, 🖼️ Asset
