Repository Wedvice/Wedvice_FE, pull requests merged in 2025-02, with the labels that each got.

#17 [chore] ESLint 및 Prettier 설정 변경
  .eslintrc.json
  .prettierrc
  .vscode/settings.json
  package.json
  src/app/home/[username]/layout.tsx
  src/app/memo/[username]/page.tsx
  src/components/atoms/memo/Memo.stories.tsx
  src/components/atoms/memo/Memo.tsx
  src/components/atoms/memo/MemoDiv.tsx
  src/components/atoms/memo/MemoTextarea.tsx
  src/components/atoms/profile/Profile.tsx
  src/components/molecules/MemoContent.tsx
  src/features/home/Home.tsx
  src/features/memo/Memo.tsx
  src/features/memo/index.ts
  yarn.lock
Labels: ⚙ Setting

#11 [feat] 카카오 Auth 관련 로그인
  public/kakao_login_medium_wide.png
  src/app/Redirection/Redirection.tsx
  src/app/Redirection/page.tsx
  src/app/page.tsx
  src/features/components/LoginButton.tsx
Labels: ✨ Feature

#20 [Feat] BottomSheet 컴포넌트 생성
  package.json
  src/components/atoms/bottomSheet/BottomSheet.stories.tsx
  src/components/atoms/bottomSheet/BottomSheet.tsx
  src/components/atoms/bottomSheet/index.ts
  src/components/atoms/bottomSheet/style.css
  yarn.lock
Labels: ✨ Feature, ⚙ Setting

#19 [feat] 메모 기능 추가 구현 및 context api 구조 적용
  src/app/layout.tsx
  src/components/atoms/memo/Memo.tsx
  src/components/atoms/memo/MemoDiv.tsx
  src/components/atoms/memo/MemoTextarea.tsx
  src/components/atoms/memo/SubmitButton.tsx
  src/components/molecules/memo/MemoContent.tsx
  src/components/molecules/memo/MemoLink.tsx
  src/constants/memo/memoConstants.ts
  src/contexts/memo/MemoContext.ts
  src/contexts/memo/MemoProvider.tsx
  src/features/home/Home.tsx
  src/features/memo/Memo.tsx
  src/types/memo/memoTypes.ts
  src/utils/memo/memoUtils.ts
Labels: ✨ Feature

#15 [feat] 달력 선택 컴포넌트 구현
  package.json
  src/components/molecules/calendarSelect/CalendarSelect.tsx
  src/components/molecules/calendarSelect/index.ts
  src/components/molecules/calendarSelect/styles.css
Labels: ✨ Feature

#18 [feat] TextInput, TextArea 컴포넌트 구현
  src/components/atoms/textArea/TextArea.stories.tsx
  src/components/atoms/textArea/TextArea.tsx
  src/components/atoms/textInput/TextInput.stories.tsx
  src/components/atoms/textInput/TextInput.tsx
  src/utils/validation.ts
Labels: ✨ Feature

#25 [chore] amend 시 Prefix가 추가되지 않도록 예외 처리
  .husky/prepare-commit-msg
Labels: ⚙ Setting

#26 [chore] husky 패키지 매니저 npx -> yarn 변경
  .husky/commit-msg
  yarn.lock
Labels: ⚙ Setting, 🐞 BugFix

#29 [refactor] memo 구조 변경 및 bugfix
  src/components/atoms/memo/Memo.stories.tsx
  src/components/molecules/memo/MemoContent.tsx
  src/components/molecules/memo/MemoLink.tsx
  src/features/memo/component/Memo.stories.tsx
  src/features/memo/component/Memo.tsx
  src/features/memo/component/MemoTextarea.tsx
  src/features/memo/component/SubmitButton.tsx
Labels: 🔨 Refactor, 🐞 BugFix

#28 [chore] prettier-plugin-tailwindcss 적용 가능하게끔 설정
  .prettierrc
  prettier.config.cjs
Labels: ⚙ Setting, 🐞 BugFix

#32 [chore] 코드 오너 추가
  .github/CODEOWNERS
Labels: ⚙ Setting

#24 [feat] Modal 컴포넌트 구현
  src/components/atoms/modal/Modal.stories.tsx
  src/components/atoms/modal/Modal.tsx
  src/components/atoms/modal/index.ts
Labels: ✨ Feature

#23 [feat] 카테고리 및 달력, 담당자 선택 컴포넌트 구현
  src/components/molecules/calendarSelect/CalendarSelect.tsx
  src/components/molecules/categorySelect/CategorySelect.tsx
  src/components/molecules/categorySelect/index.ts
  src/components/molecules/foldableSelector/FoldableSelector.stories.tsx
  src/components/molecules/foldableSelector/FoldableSelector.tsx
  src/components/molecules/foldableSelector/index.ts
  src/components/molecules/managerSelect/ManagerSelect.tsx
  src/components/molecules/managerSelect/index.ts
Labels: ✨ Feature, 🔨 Refactor

#34 [refactor] TextInput, TextArea 컴포넌트 리팩토링
  src/components/atoms/textArea/TextArea.tsx
  src/components/atoms/textInput/TextInput.tsx
  src/utils/validation.ts
Labels: 🔨 Refactor
